// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const datasourceUrl = process.env["DATABASE_URL"];
if (!datasourceUrl) {
  throw new Error("DATABASE_URL environment variable is not set. Please configure it in your .env file.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  // NOTE: migrations are disabled during development — using `prisma db push` instead.
  // Re-enable when moving to production and you want tracked migrations:
  // migrations: {
  //   path: "prisma/migrations",
  // },
  datasource: {
    url: datasourceUrl,
  },
});
