// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "path";
import { defineConfig } from "prisma/config";

// For SQLite: resolve the database path relative to the project root
const isPostgres = process.env["DATABASE_URL"]?.startsWith("postgresql");
const datasourceUrl = isPostgres
  ? process.env["DATABASE_URL"]!
  : `file:${path.join(__dirname, "prisma", "dev.db")}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
